# A friendly name for your workflow that will appear in the GitHub Actions tab.
name: Build executables

# The event that triggers this workflow.
# This workflow will run whenever a tag is pushed.
on:
  push:
    tags:
      # Use '*' to match any tag name.
      - "v*.*.*"

# Define the jobs that will run as part of this workflow.
jobs:
  build:
    # Use a strategy matrix to run the same job on multiple operating systems.
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    
    # Define the steps to be executed within the job.
    steps:
      # Step 1: Checkout the repository code. This is essential for all workflows.
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Step 2: Set up the Python environment.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify the Python version to use

      # Step 3: Run commands to verify the installation.
      - name: Verify Python Installation
        run: |
          python --version
          pip --version