# A friendly name for your workflow that will appear in the GitHub Actions tab.
name: "build executables"

# The event that triggers this workflow.
# This workflow will run whenever a tag is pushed.
on:
  push:
    tags:
      # Use '*' to match any tag name.
      - "v*.*.*"

# Define the jobs that will run as part of this workflow.
jobs:
  build:
    # Use a strategy matrix to run the same job on multiple operating systems.
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}